# 是否生成示例配置文件
generate_examples: true  # true

# 是否取消原版暴击特效, 伤害特效
cancel_generic_particles: true  # false

# 是否生成伤害文本显示
generate_damage_indicator: true  # false
damage_indicator:
  default_prefix: "§6"  # 非暴击指示器颜色
  critical_prefix: "§4" # 暴击指示器颜色
  critical_large_scale: 2 # 所有指示器默认放大1.5倍
  view_range: 20.0  # 可见范围

# 其他的