# 只能修需要显示的中文值，请勿删减
critical_strike_chance: "暴击率"
critical_strike_damage: "暴击伤害"
skill_cooldown: "技能冷却"
skill_mana_cost: "蓝耗"
# 原版
attack_damage: "攻击伤害"
attack_speed: "攻击速度"
attack_knockback: "攻击击退"
knockback_resistance: "击退抗性"
armor: "护甲值"
armor_toughness: "护甲韧性"
burning_time: "燃烧时间"
explosion_knockback_resistance: "爆炸击退抗性"
fall_damage_multiplier: "摔落伤害乘数"
flying_speed: "飞行速度"
gravity: "重力"
jump_strength: "跳跃强度"
luck: "幸运值"
max_absorption: "护甲伤害最大吸收值"
max_health: "最大生命值"
movement_efficiency: "困难地形移动速度"
movement_speed: "移动速度"
oxygen_bonus: "水下可使用氧气"
safe_fall_distance: "安全摔落距离"
scale: "尺寸"
step_height: "可跨越高度"
water_movement_efficiency: "水中移动速度"
player_block_break_speed: "方块破坏速度"
player_block_interaction_range: "方块交互范围"
player_entity_interaction_range: "实体交互范围"
player_mining_efficiency: "挖掘效率"
player_sneaking_speed: "潜行速度"
player_submerged_mining_speed: "水下挖掘速度"
player_sweeping_damage_ratio: "横扫伤害比例"
