# 只能修需要显示的中文值，请勿删减
critical-strike-chance: "暴击率"
critical-strike-damage: "暴击伤害"
skill-cooldown: "技能冷却"
skill-mana-cost: "蓝耗"
# 原版
attack-damage: "攻击伤害"
attack-speed: "攻击速度"
attack-knockback: "攻击击退"
knockback-resistance: "击退抗性"
armor: "护甲值"
armor-toughness: "护甲韧性"
burning-time: "燃烧时间"
explosion-knockback-resistance: "爆炸击退抗性"
fall-damage-multiplier: "摔落伤害乘数"
flying-speed: "飞行速度"
gravity: "重力"
jump-strength: "跳跃强度"
luck: "幸运值"
max-absorption: "护甲伤害最大吸收值"
max-health: "最大生命值"
movement-efficiency: "困难地形移动速度"
movement-speed: "移动速度"
oxygen-bonus: "水下可使用氧气"
safe-fall-distance: "安全摔落距离"
scale: "尺寸"
step-height: "可跨越高度"
water-movement-efficiency: "水中移动速度"
player-block-break-speed: "方块破坏速度"
player-block-interaction-range: "方块交互范围"
player-entity-interaction-range: "实体交互范围"
player-mining-efficiency: "挖掘效率"
player-sneaking-speed: "潜行速度"
player-submerged-mining-speed: "水下挖掘速度"
player-sweeping-damage-ratio: "横扫伤害比例"
