# 所支持的 minimessage 格式
# <gradient>TEXT_TO_DISPLAY</gradient>
# <#fffff>TEXT_TO_DISPLAY

# 可更改的属性(attrs)：
# attack_damage、critical_strike_chance、critical_strike_damage、
# skill_cooldown、mana_cost、armor、armor_toughness、
# pre_armor_reduction、after_armor_reduction
品质组名:
  # 带百分号为乘算 否则为加算
  <red>品质1</red>:
    slot: any  # MC支持的物品佩戴位置  # 默认为ANY
    weight: 1  # 品质的权重用于随机选择 必写
    attrs:
      # key不能相同
      # 表示在数值上使用乘算
      attack_damage: "_10%"

  # 品质显示的名称为(蓝色的）品质2
  <blue>品质2</blue>:
    weight: 1
    attrs:
      critical_strike_chance: "_10"
      critical_strike_damage: "_10"
  品质3:
    weight: 1
    attrs:
      skill_cooldown: "_10%"  # 技能冷却 (所有)
      skill_mana_cost: "_10%"  # 技能蓝耗 (所有)
  品质4:
    weight: 1
    attrs:
      armor: "+5"
      armor_toughness: "+5"
  品质5:
    weight: 1.2

品质组名1:
  <#123456>伤害测试:
    weight: 2
    attrs:
      attack_damage: "+5"
