# 所支持的 minimessage 格式
# <gradient>TEXT_TO_DISPLAY</gradient>
# <#fffff>TEXT_TO_DISPLAY

# 可更改的属性(attrs)：
# attack-damage、critical-strike-chance、critical-strike-damage、
# skill-cooldown、mana-cost、armor、armor-toughness、
# pre-armor-reduction、after-armor-reduction
品质组名:
  # 带百分号为乘算 否则为加算
  <red>品质1</red>:
    slot: any  # MC支持的物品佩戴位置  # 默认为ANY
    weight: 1  # 品质的权重用于随机选择 必写
    attrs:
      # key不能相同
      # 表示在数值上使用乘算
      attack-damage: "-10%"

  # 品质显示的名称为(蓝色的）品质2
  <blue>品质2</blue>:
    weight: 1
    attrs:
      critical-strike-chance: "-10"
      critical-strike-damage: "-10"
  品质3:
    weight: 1
    attrs:
      skill-cooldown: "-10%"  # 技能冷却 (所有)
      skill-mana-cost: "-10%"  # 技能蓝耗 (所有)
  品质4:
    weight: 1
    attrs:
      armor: "+5"
      armor-toughness: "+5"
  品质5:
    weight: 1.2

品质组名1:
  <#123456>伤害测试:
    weight: 2
    attrs:
      attack-damage: "+5"
