技能1:
  name: test1  # 与 mm 技能同名
  cd: 1  # (秒)  # 受到技能cd减免影响
  mana: 10  # 蓝量消耗 （正数为减少，负数增加）
  damage_k: 0.5 # 面板伤害乘数(1)  也会进入伤害计算
  can_critical_strike: true # 遵循武器面板暴击概率

技能2:
  cfg: test2

技能3:
  cfg: test3