增益名:
  # 具体属性
  priority: 0
  attributeCalculateSection: ADD # 必写（基础属性，不能自定义行为，只能在伤害计算中被动使用）
  damage: 0
  armor: 0
  critical_strike_chance: 0.8
  critical_strike_damage: 1.5
  armor_toughness: 0
  pre_armor_reduction: 0
  after_armor_reduction: 0
  mana_cost: _0.1
  skill_cooldown: _0.1
  # 玩家伤害属性增加
  melee: 0.1  # 战士伤害
  magic: 0.1  # 法师伤害
  ranged: 0.1 # 射手伤害
  rouge: 0.1  # 盗贼伤害
  summon: 0.1 # 召唤伤害
  other: 0.01 # 其他
